[tools]
node = "22.17.0"
pnpm = "10.12.4"

[env]
_.path = "node_modules/.bin"
_.file = ".env"

[settings]
experimental = true

[hooks]
postinstall = [
    "pnpm install ${CI:+--frozen-lockfile}",
    "mise run sync-versions",
]

[tasks.sync-versions]
run = """
NODE_VERSION="v$(grep '^node = ' mise.toml | cut -d'"' -f2)"
PNPM_VERSION="v$(grep '^pnpm = ' mise.toml | cut -d'"' -f2)"
sed -i.bak -e "s/^NODE_VERSION = .*/NODE_VERSION = \\"$NODE_VERSION\\"/" \
           -e "s/^PNPM_VERSION = .*/PNPM_VERSION = \\"$PNPM_VERSION\\"/" wrangler.toml
rm -f wrangler.toml.bak
echo "Updated wrangler.toml: NODE_VERSION=$NODE_VERSION, PNPM_VERSION=$PNPM_VERSION"
"""

[tasks.dev]
run = "astro dev"

[tasks.start]
run = "astro dev"

[tasks.test]
run = "vitest"

[tasks.build]
run = "astro check && astro build"

[tasks.preview]
run = "astro preview"

[tasks.astro]
run = "astro"

[tasks.logs]
run = "wrangler pages deployment tail --project-name just-be-dev"

[tasks."logs:preview"]
run = "wrangler pages deployment tail --project-name just-be-dev --environment preview"
