[tools]
node = "22.17.0"
pnpm = "10.12.4"

[env]
_.path = "node_modules/.bin"
_.file = ".env"

[tasks.dev]
run = "astro dev"

[tasks.start]
run = "astro dev"

[tasks.test]
run = "vitest"

[tasks.build]
run = "astro check && astro build"

[tasks.preview]
run = "astro preview"

[tasks.astro]
run = "astro"

[tasks.logs]
run = "wrangler pages deployment tail --project-name just-be-dev"

[tasks."logs:preview"]
run = "wrangler pages deployment tail --project-name just-be-dev --environment preview"
