// Generated by Wrangler on Wed Aug 07 2024 20:05:22 GMT-0400 (Eastern Daylight Time)
// by running `wrangler types`

interface Env {
	KV_MAPPINGS: KVNamespace;
	PUBLISH_KEY: string;
	R2_BUCKET: R2Bucket;
}
