// Generated by Wrangler by running `wrangler types`

interface Env {
	KV_MAPPINGS: KVNamespace;
	KV_HIGHLIGHT: KVNamespace;
	NODE_VERSION: "v20.16.0";
	PNPM_VERSION: "v9.7.0";
	SITE: string;
	PUBLISH_KEY: string;
	SENTRY_DSN: string;
	SENTRY_AUTH_TOKEN: string;
	R2_BUCKET: R2Bucket;
	R2_ASSETS: R2Bucket;
}
