name = "just-be.dev"
main = "src/index.ts"
compatibility_date = "2022-11-27"

kv_namespaces = [
  { binding = "KV_IDs", id = "9b50bb86675242f493b168d0feb3ecfc" },
  { binding = "KV_URLs", id = "8e76f1a51eb94a918b04bb2c0816a84a" },
]
