name = "just-be-dev"
compatibility_date = "2022-11-27"
compatibility_flags = [ "formdata_parser_supports_files" ]

kv_namespaces = [
  { binding = "KV_IDs", id = "9b50bb86675242f493b168d0feb3ecfc" },
  { binding = "KV_FILENAMEs", id = "d5a9d75ba4214c4eb50dfb8292df5fcb" },
  { binding = "KV_URLs", id = "8e76f1a51eb94a918b04bb2c0816a84a" },
  { binding = "KV_NOTEs", id = "8b8e357f669b4f1c87223779f3185605" }
]

r2_buckets = [
  { binding = "R2_ATTACHMENTS", bucket_name = "attachments" },
]
