name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup mise
        uses: jdx/mise-action@v2
        with:
          install: true

      - name: Run Vitest
        run: mise run test

      - name: Run Astro check
        run: mise run astro check

      - name: Run Astro build
        run: mise run build
